"""
Common Tactical Object (CTO) schema.

This module defines the canonical normalized representation for all
tactical data that flows through the gateway. Every inbound message,
regardless of source protocol (CoT XML, CoT protobuf, OTH-Gold, KML/KMZ,
etc.), is converted to a CTO before being stored or forwarded. Every
outbound message is generated by converting a CTO to the target
protocol.

Design principle: the CTO is a SUPERSET. It must be possible to convert
any input protocol to a CTO without losing information. Information loss
is permitted only at egress, when the target protocol cannot represent
a field, and such losses must be logged via the `provenance` field.

The `attributes` open key-value field is the escape hatch: any
protocol-specific data that does not fit a typed field goes there. This
keeps ingest lossless even as the typed schema evolves.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class SourceProtocol(str, Enum):
    """Wire protocol the object was received as."""

    COT_XML = "cot_xml"
    COT_PROTOBUF = "cot_protobuf"
    OTH_GOLD = "oth_gold"
    KML = "kml"
    KMZ = "kmz"
    INTERNAL = "internal"  # produced by the gateway itself


class ObjectClass(str, Enum):
    """High-level classification of what the object represents."""

    TRACK = "track"  # a moving entity with a position
    POINT = "point"  # a static point of interest
    AREA = "area"  # a polygon (engagement area, no-strike, etc.)
    ROUTE = "route"  # a polyline route or boundary
    SYMBOL = "symbol"  # a tactical graphic / 2525 symbol
    OVERLAY = "overlay"  # a container for multiple sub-objects
    TEXT_ANNOTATION = "text_annotation"  # free-form text tied to a location


class Classification(str, Enum):
    """U.S. classification levels in scope for this system."""

    UNCLASSIFIED = "U"
    CUI = "CUI"
    SECRET = "S"


class Affiliation(str, Enum):
    """MIL-STD-2525 affiliation (standard identity)."""

    PENDING = "pending"
    UNKNOWN = "unknown"
    ASSUMED_FRIEND = "assumed_friend"
    FRIEND = "friend"
    NEUTRAL = "neutral"
    SUSPECT = "suspect"
    HOSTILE = "hostile"


class BattleDimension(str, Enum):
    """MIL-STD-2525 battle dimension."""

    SPACE = "space"
    AIR = "air"
    LAND = "land"
    SEA_SURFACE = "sea_surface"
    SEA_SUBSURFACE = "sea_subsurface"
    SOF = "sof"
    OTHER = "other"


class AltitudeSource(str, Enum):
    GPS = "gps"
    BAROMETRIC = "barometric"
    DERIVED = "derived"
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Geometry (GeoJSON-compatible)
# ---------------------------------------------------------------------------


class Geometry(BaseModel):
    """GeoJSON-style geometry in WGS84.

    Coordinates are [longitude, latitude] per GeoJSON convention.
    Altitude is carried separately on the CTO, not in coordinates.
    """

    model_config = ConfigDict(frozen=True)

    type: Literal["Point", "LineString", "Polygon", "MultiPoint", "MultiLineString", "MultiPolygon"]
    coordinates: list[Any]  # shape depends on type; validated below

    @field_validator("coordinates")
    @classmethod
    def coords_not_empty(cls, v: list[Any]) -> list[Any]:
        if not v:
            raise ValueError("geometry coordinates must not be empty")
        return v


# ---------------------------------------------------------------------------
# Sub-objects
# ---------------------------------------------------------------------------


class Symbology(BaseModel):
    """Symbol identification across notations.

    All fields optional because not every input protocol carries every
    notation; we record what we know and fill the rest when we can.
    """

    model_config = ConfigDict(frozen=True)

    mil_std_2525d_sidc: str | None = Field(
        default=None,
        description="20-character MIL-STD-2525D symbol identification code",
    )
    cot_type: str | None = Field(
        default=None,
        description="CoT type string, e.g. 'a-f-G-U-C'",
    )
    affiliation: Affiliation | None = None
    battle_dimension: BattleDimension | None = None
    echelon: str | None = Field(
        default=None,
        description="Echelon code from 2525D (e.g. 'B' for squad, 'F' for battalion)",
    )
    status: str | None = Field(
        default=None,
        description="Operational status (present, anticipated, planned, etc.)",
    )


class Altitude(BaseModel):
    """Altitude with provenance.

    HAE = height above ellipsoid (WGS84), the standard for CoT.
    """

    model_config = ConfigDict(frozen=True)

    value_m: float = Field(description="Altitude in meters HAE")
    source: AltitudeSource = AltitudeSource.UNKNOWN
    accuracy_m: float | None = Field(
        default=None,
        description="1-sigma vertical accuracy in meters, if known",
    )


class Kinematics(BaseModel):
    """Motion data for tracks."""

    model_config = ConfigDict(frozen=True)

    course_deg: float | None = Field(
        default=None, ge=0.0, lt=360.0, description="Course over ground in degrees true"
    )
    heading_deg: float | None = Field(
        default=None, ge=0.0, lt=360.0, description="Heading in degrees true"
    )
    speed_mps: float | None = Field(
        default=None, ge=0.0, description="Speed in meters per second"
    )
    vertical_rate_mps: float | None = Field(
        default=None, description="Vertical rate in meters per second (positive = climb)"
    )


class RawPointer(BaseModel):
    """Pointer to the original raw message in the capture store."""

    model_config = ConfigDict(frozen=True)

    sha256: str = Field(description="SHA-256 hex digest of the raw bytes")
    object_key: str = Field(description="MinIO object key where raw bytes are stored")
    size_bytes: int = Field(ge=0)
    captured_at: datetime


class ProvenanceEntry(BaseModel):
    """One transformation applied to produce this CTO from raw or from a prior CTO."""

    model_config = ConfigDict(frozen=True)

    step: str = Field(description="Short identifier, e.g. 'cot_xml_to_cto'")
    actor: str = Field(description="Service or module that performed the step")
    at: datetime
    notes: str | None = None
    lossy_fields: list[str] = Field(
        default_factory=list,
        description="Fields where data was dropped or approximated in this step",
    )


# ---------------------------------------------------------------------------
# The CTO itself
# ---------------------------------------------------------------------------


class CTO(BaseModel):
    """Common Tactical Object.

    The normalized representation of any geospatial / tactical datum
    flowing through the gateway. Constructed by the normalizer service
    from raw inputs; consumed by the translator service to produce
    outputs in any supported protocol.
    """

    model_config = ConfigDict(
        # CTOs are not mutated after creation. New facts produce new CTOs
        # with provenance chains back to predecessors.
        frozen=True,
        # Allow population by either field name or alias for JSON
        # interoperability with other systems.
        populate_by_name=True,
    )

    # --- Identity -----------------------------------------------------
    uid: UUID = Field(description="Globally unique CTO id (UUID v7 for time ordering)")
    source_uid: str | None = Field(
        default=None,
        description="Original ID from the source system (CoT UID, OTH message ID, etc.)",
    )
    source_system: str = Field(
        description="Logical name of the source feed, e.g. 'tak-primary', 'gccs-j-1'"
    )
    source_protocol: SourceProtocol

    # --- Temporal -----------------------------------------------------
    received_at: datetime = Field(description="When the gateway received the raw input")
    event_time: datetime = Field(description="When the event itself occurred (per the source)")
    valid_from: datetime | None = Field(
        default=None, description="Start of validity window (CoT 'start')"
    )
    valid_to: datetime | None = Field(
        default=None, description="End of validity window (CoT 'stale')"
    )

    # --- Classification & dissemination ------------------------------
    classification: Classification = Classification.UNCLASSIFIED
    caveats: list[str] = Field(
        default_factory=list,
        description="Dissemination caveats (e.g. 'NOFORN', 'FVEY')",
    )

    # --- What & where ------------------------------------------------
    object_class: ObjectClass
    geometry: Geometry
    altitude: Altitude | None = None
    kinematics: Kinematics | None = None
    symbology: Symbology = Field(default_factory=Symbology)

    # --- Human-readable ----------------------------------------------
    callsign: str | None = None
    label: str | None = Field(default=None, description="Display label, distinct from callsign")
    remarks: str | None = None

    # --- Open extension ----------------------------------------------
    attributes: dict[str, Any] = Field(
        default_factory=dict,
        description="Protocol-specific fields that don't fit the typed schema. "
        "Used to preserve information at ingest that may or may not be "
        "representable at egress.",
    )

    # --- Capture & lineage -------------------------------------------
    raw_pointer: RawPointer
    provenance: list[ProvenanceEntry] = Field(default_factory=list)

    @field_validator("event_time", "received_at", "valid_from", "valid_to")
    @classmethod
    def require_tz(cls, v: datetime | None) -> datetime | None:
        if v is not None and v.tzinfo is None:
            raise ValueError("datetimes must be timezone-aware (UTC preferred)")
        return v

    @field_validator("received_at")
    @classmethod
    def normalize_to_utc(cls, v: datetime) -> datetime:
        return v.astimezone(timezone.utc)
